---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-funcx-serialization-service
spec:
  ports:
   - port: 8001
     targetPort: 5000
     name: "tcp"
     protocol: TCP
  selector:
    app: {{ .Release.Name }}-funcx-serialization-service
  type: ClusterIP
